import DashboardNavbar from "@/components/dashboard/dash-navbar";
import SidePanel from "@/components/dashboard/sidepanel";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="sticky top-0 bg-landing_background text-foreground">
        <DashboardNavbar />
        <div className="flex">
          <SidePanel />
          <main className="flex-1 bg-white">{children}</main>
        </div>
      </body>
    </html>
  );
}
